# This file was generated by GoReleaser. DO NOT EDIT.
cask "roger" do
  version "5.2.1"

  on_macos do
    on_intel do
      sha256 "5ca0d5d027e33e23d33ac36a5d87e9d4f3771210c605a5b3e1a556e5ffc5d757"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-amd64"
      binary "roger-darwin-amd64", target: "roger"
    end
    on_arm do
      sha256 "a2b5a7f9647d0131b4d4e193ac28dcd7e0c5e3a93a65e9cf0d4c9ec134ced27e"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-arm64"
      binary "roger-darwin-arm64", target: "roger"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0f63dc5df6443066cfff798c0f25aeb386e73fd35c56df04de3dc61abbd671b"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-amd64"
      binary "roger-linux-amd64", target: "roger"
    end
    on_arm do
      sha256 "f22771c61b8b352eda1c9e86bc61bffcd23f0ff2f68e65cb05bd50c5645a691a"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-arm64"
      binary "roger-linux-arm64", target: "roger"
    end
  end

  name "roger"
  desc "RogerAI - a two-way radio for GPUs. Consume and share LLM/voice models over the broker."
  homepage "https://rogerai.fyi"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
