# This file was generated by GoReleaser. DO NOT EDIT.
cask "roger" do
  version "5.2.0"

  on_macos do
    on_intel do
      sha256 "e45a035bed0603e11301abcde64d261df5c5337c262c44d22107be33cb1c3f0a"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-amd64"
      binary "roger-darwin-amd64", target: "roger"
    end
    on_arm do
      sha256 "326c8361678779e03aa36dcc217c8a609430145a0484c35a480e192f1fa3eda6"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-arm64"
      binary "roger-darwin-arm64", target: "roger"
    end
  end

  on_linux do
    on_intel do
      sha256 "66591def7ccc7756829c2bd8b724ee2c23b7d1e687748d4edd8ab5064c86db4d"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-amd64"
      binary "roger-linux-amd64", target: "roger"
    end
    on_arm do
      sha256 "3dbc055a94e4a3e1bb0a636327f444074a62c486ec433a1174045d4c68f88022"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-arm64"
      binary "roger-linux-arm64", target: "roger"
    end
  end

  name "roger"
  desc "RogerAI - a two-way radio for GPUs. Consume and share LLM/voice models over the broker."
  homepage "https://rogerai.fyi"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
