# This file was generated by GoReleaser. DO NOT EDIT.
cask "roger" do
  version "5.1.0"

  on_macos do
    on_intel do
      sha256 "f8a5ff9040b57a7e4c56fa4f869843e199075874bec7c74060911f325f079543"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-amd64"
      binary "roger-darwin-amd64", target: "roger"
    end
    on_arm do
      sha256 "df20aa63aec96160629a161efe5af2909e25ce829f3013061d68ed5f0355ffb0"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-arm64"
      binary "roger-darwin-arm64", target: "roger"
    end
  end

  on_linux do
    on_intel do
      sha256 "2702209dc7d73846b75cf367a211508138abad67e1e8b1ffb49593f13bc2e2ef"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-amd64"
      binary "roger-linux-amd64", target: "roger"
    end
    on_arm do
      sha256 "de830f0a18249f9d6d5ae73acb87aab4893f939393a1a589afa2ad2163f9e9e2"
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-arm64"
      binary "roger-linux-arm64", target: "roger"
    end
  end

  name "roger"
  desc "RogerAI - a two-way radio for GPUs. Consume and share LLM/voice models over the broker."
  homepage "https://rogerai.fyi"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
