# This file is generated by scripts/gen-brew-formula.sh from the release checksums.txt.
# DO NOT EDIT — re-run the generator (or cut a new release) to update.
class Roger < Formula
  desc "Two-way radio for GPUs: consume and share LLM/voice models over the broker"
  homepage "https://rogerai.fyi"
  version "5.4.3"
  # PolyForm Perimeter 1.0.0 — source-available, not an SPDX id, so `brew audit` can't
  # match it; :cannot_represent is Homebrew's blessed value for exactly this case.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-arm64"
      sha256 "05bff5d475e34efd679fbee4d1625c8e31027b46359b552c0943f9a2d4c79ccf"
    end
    on_intel do
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-amd64"
      sha256 "3290f0bab4eee0245b5514a975650ace4464a2bd8c85cfdef87c62a714046875"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-arm64"
      sha256 "299b96b83667b923d4c9b87d9a8123c98ab445ca250d02c7058bb279a4b50361"
    end
    on_intel do
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-amd64"
      sha256 "dba675af4cc929fee584b684326166f1a83502fa88e509f54920a91a2f70dcc7"
    end
  end

  def install
    bin.install Dir["*"].first => "roger"
  end

  test do
    assert_match "roger", shell_output("#{bin}/roger version 2>&1")
  end
end
