# This file is generated by scripts/gen-brew-formula.sh from the release checksums.txt.
# DO NOT EDIT — re-run the generator (or cut a new release) to update.
class Roger < Formula
  desc "Two-way radio for GPUs: consume and share LLM/voice models over the broker"
  homepage "https://rogerai.fyi"
  version "5.2.2"
  # PolyForm Perimeter 1.0.0 — source-available, not an SPDX id, so `brew audit` can't
  # match it; :cannot_represent is Homebrew's blessed value for exactly this case.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-arm64"
      sha256 "326d73388762bb9de4d714ac3c96f940741be030d828c61a1512acdafd137c70"
    end
    on_intel do
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-darwin-amd64"
      sha256 "6cfdcfd5162d6890ffa28b2560a255e338a1a5070474470759df32c6366e6a3f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-arm64"
      sha256 "a3511fd8ad9a71a18f4b4510307b601441b5fb67897262940849ea8b395e9795"
    end
    on_intel do
      url "https://github.com/rogerai-fyi/roger/releases/download/v#{version}/roger-linux-amd64"
      sha256 "dfaca814a924bc758ec6006122af993d53580b5d2c2bfdecd6acc82113c18713"
    end
  end

  def install
    bin.install Dir["*"].first => "roger"
  end

  test do
    assert_match "roger", shell_output("#{bin}/roger version 2>&1")
  end
end
